services:
  db:
    image: postgres:16
    container_name: soc_postgres
    environment:
      POSTGRES_DB: soctriage
      POSTGRES_USER: soctriage
      POSTGRES_PASSWORD: soctriage
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
